### ISSUE TITLE
If change Consent

### ISSUE THREAD

**Issue by sbenahmedNB** [didomi/samples#4]
What happen if we change consent ? 

Now if we change the consent the Youtube player charge and the overlay don't apear. 

How i can solve this ?

Thank you.

**Comment by dvdtsr** [comment]
Just to clarify, is the following scenario what you have in mind?

- Open the [page](https://didomi.github.io/samples/how-to-embed-youtube/) and click "accept all" on the cookie banner
=> the Youtube video plays
- Reopen the notice and click "refuse all"
=> The youtube video keeps playing and the overlay doesn't reappears.


If so, this is normal behavior: the user is giving consent for the video to play.
If he later changes his mind, there's no way to "undo" his previous acceptance, so there's no need to hide the video behind the overlay.
But since the overlay reappears after the page reloads, the new negative consent status is correctly taken into account, which is compliant behavior.
